# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0002_verifydata_submit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artcle', models.TextField(max_length=1000)),
                ('publice_time', models.TimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
    ]
