# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shorthand',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
