# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0004_blog_shorthand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lava.School'),
        ),
    ]
