# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0005_auto_20180328_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publice_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
