# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildlist', models.CharField(default='', max_length=1000)),
                ('build_id', models.CharField(default='', max_length=50)),
                ('submit_user', models.CharField(default='', max_length=50)),
                ('verify_url', models.CharField(default='', max_length=50)),
                ('gerrit_id', models.CharField(default='', max_length=50)),
                ('port', models.CharField(default='', max_length=50)),
                ('compile_user', models.CharField(default='', max_length=50)),
                ('module', models.CharField(default='', max_length=50)),
                ('test_cases', models.CharField(default='', max_length=50)),
                ('manual_test_case', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('test_description', models.CharField(default='', max_length=50)),
                ('project_num', models.CharField(default='', max_length=50)),
                ('test_task_type', models.CharField(default='', max_length=50)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
