# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_v2_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifydata',
            name='submitted_flag',
            field=models.IntegerField(default=0),
        ),
    ]
