# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_v2_queue', '0004_auto_20180413_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifydatatmp',
            name='poped_flag',
            field=models.IntegerField(default=0),
        ),
    ]
